In [1]:
# Dependancies
import pandas as pd
import os
import numpy as np

In [2]:
# Loading Files -
crime_model_data_to_load = os.path.join("Resources","clean_pop_zip_model.csv")
chipotle_zip_data_to_load = os.path.join("Resources", 'new_chipotle_data.csv')

In [3]:
# reading  data into dataframe for merging
chip_zip_df = pd.read_csv(chipotle_zip_data_to_load,header=0, delim_whitespace=False)
chip_zip_df

,state,location,address,latitude,longitude,ZIP
0,Alabama,Auburn,"346 W Magnolia Ave Auburn, AL 36832 US",32.606813,-85.487328,36832
1,Alabama,Birmingham,"300 20th St S Birmingham, AL 35233 US",33.509721,-86.802756,35233
2,Alabama,Birmingham,"3220 Morrow Rd Birmingham, AL 35235 US",33.595581,-86.647437,35235
3,Alabama,Birmingham,"4719 Highway 280 Birmingham, AL 35242 US",33.422582,-86.698279,35242
4,Alabama,Cullman,"1821 Cherokee Ave SW Cullman, AL 35055 US",34.154134,-86.841220,35055
...,...,...,...,...,...,...
2624,Wisconsin,Pleasant Prairie,"9370 76th St # B Pleasant Prairie, WI 53158 US",42.565892,-87.921048,53158
2625,Wisconsin,Wauwatosa,"2711 N Mayfair Rd Ste A Wauwatosa, WI 53222 US",43.067723,-88.048222,53222
2626,North Dakota,Fargo,"1204 19th Ave N Fargo, ND 58102 US",46.904247,-96.796618,58102
2627,North Dakota,Fargo,"1680 45th St S Fargo, ND 58103 US",46.855337,-96.861416,58103
2628,Wyoming,Cheyenne,"1508 Dell Range Blvd Cheyenne, WY 82009 US",41.160718,-104.805699,82009

In [4]:
chip_zip_df['chipotle']=1

In [5]:
# reading in data into dataframe for merging

crime_data_df = pd.read_csv(crime_model_data_to_load, header=0, delim_whitespace=False)
crime_data_df

,Unnamed: 0,ZIP,Ward,Primary Type,rankings,Latitude,Longitude,Arrest,Domestic,Population,People/Sq.Mile,National Rank
0,0,60601,27,THEFT,3,NaN,NaN,False,False,"5,591","17,101.15",#271
1,1,60601,27,CRIMINAL DAMAGE,4,41.883932,-87.679964,False,False,"5,591","17,101.15",#271
2,2,60601,27,THEFT,3,41.896569,-87.636063,False,False,"5,591","17,101.15",#271
3,3,60601,27,SEX OFFENSE,3,41.883937,-87.683368,True,False,"5,591","17,101.15",#271
4,4,60601,27,NARCOTICS,4,41.892856,-87.710137,True,False,"5,591","17,101.15",#271
...,...,...,...,...,...,...,...,...,...,...,...,...
105624,105624,60661,30,OTHER OFFENSE,3,41.941430,-87.737110,False,True,"4,382","15,455.28",#318
105625,105625,60661,30,MOTOR VEHICLE THEFT,6,NaN,NaN,False,False,"4,382","15,455.28",#318
105626,105626,60661,30,OFFENSE INVOLVING CHILDREN,3,41.940857,-87.728919,False,False,"4,382","15,455.28",#318
105627,105627,60661,30,BATTERY,4,41.940049,-87.719873,False,True,"4,382","15,455.28",#318
105628,105628,60661,30,ROBBERY,8,41.923901,-87.771157,False,False,"4,382","15,455.28",#318

In [6]:
crime_data_df.set_index('ZIP', inplace=True)
chip_zip_df.set_index('ZIP', inplace=True)

In [7]:

crime_chip_df = pd.merge(crime_data_df, chip_zip_df, on='ZIP', how='outer')
crime_chip_df.reset_index('ZIP', drop=False, inplace=True)

crime_chip_df

,ZIP,Unnamed: 0,Ward,Primary Type,rankings,Latitude,Longitude,Arrest,Domestic,Population,People/Sq.Mile,National Rank,state,location,address,latitude,longitude,chipotle
0,60601,0.0,27.0,THEFT,3.0,NaN,NaN,False,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
1,60601,1.0,27.0,CRIMINAL DAMAGE,4.0,41.883932,-87.679964,False,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
2,60601,2.0,27.0,THEFT,3.0,41.896569,-87.636063,False,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
3,60601,3.0,27.0,SEX OFFENSE,3.0,41.883937,-87.683368,True,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
4,60601,4.0,27.0,NARCOTICS,4.0,41.892856,-87.710137,True,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123681,53158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wisconsin,Pleasant Prairie,"9370 76th St # B Pleasant Prairie, WI 53158 US",42.565892,-87.921048,1.0
123682,53222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wisconsin,Wauwatosa,"2711 N Mayfair Rd Ste A Wauwatosa, WI 53222 US",43.067723,-88.048222,1.0
123683,58102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Dakota,Fargo,"1204 19th Ave N Fargo, ND 58102 US",46.904247,-96.796618,1.0
123684,58103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,North Dakota,Fargo,"1680 45th St S Fargo, ND 58103 US",46.855337,-96.861416,1.0
123685,82009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,Cheyenne,"1508 Dell Range Blvd Cheyenne, WY 82009 US",41.160718,-104.805699,1.0

In [8]:
crime_chip_df_filtered = crime_chip_df[crime_chip_df['rankings'] >=1.0]

crime_chip_df_filtered

,ZIP,Unnamed: 0,Ward,Primary Type,rankings,Latitude,Longitude,Arrest,Domestic,Population,People/Sq.Mile,National Rank,state,location,address,latitude,longitude,chipotle
0,60601,0.0,27.0,THEFT,3.0,NaN,NaN,False,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
1,60601,1.0,27.0,CRIMINAL DAMAGE,4.0,41.883932,-87.679964,False,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
2,60601,2.0,27.0,THEFT,3.0,41.896569,-87.636063,False,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
3,60601,3.0,27.0,SEX OFFENSE,3.0,41.883937,-87.683368,True,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
4,60601,4.0,27.0,NARCOTICS,4.0,41.892856,-87.710137,True,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121081,60661,105624.0,30.0,OTHER OFFENSE,3.0,41.941430,-87.737110,False,True,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1.0
121082,60661,105625.0,30.0,MOTOR VEHICLE THEFT,6.0,NaN,NaN,False,False,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1.0
121083,60661,105626.0,30.0,OFFENSE INVOLVING CHILDREN,3.0,41.940857,-87.728919,False,False,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1.0
121084,60661,105627.0,30.0,BATTERY,4.0,41.940049,-87.719873,False,True,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1.0
121085,60661,105628.0,30.0,ROBBERY,8.0,41.923901,-87.771157,False,False,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1.0

In [9]:
crime_chip_df_filtered.dtypes

ZIP                 int64
Unnamed: 0        float64
Ward              float64
Primary Type       object
rankings          float64
Latitude          float64
Longitude         float64
Arrest             object
Domestic           object
Population         object
People/Sq.Mile     object
National Rank      object
state              object
location           object
address            object
latitude          float64
longitude         float64
chipotle          float64
dtype: object

In [10]:


crime_chip_df_filtered['chipotle'] = crime_chip_df_filtered['chipotle'].fillna(0).astype(int)
crime_chip_df_filtered
crime_chip_df_filtered.dtypes

C:\Users\karla\anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

ZIP                 int64
Unnamed: 0        float64
Ward              float64
Primary Type       object
rankings          float64
Latitude          float64
Longitude         float64
Arrest             object
Domestic           object
Population         object
People/Sq.Mile     object
National Rank      object
state              object
location           object
address            object
latitude          float64
longitude         float64
chipotle            int32
dtype: object

In [12]:
crime_chip_df_filtered.drop('Unnamed: 0', axis=1, inplace=True)
crime_chip_df_filtered

C:\Users\karla\anaconda3\envs\pythondata\lib\site-packages\pandas\core\frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,ZIP,Ward,Primary Type,rankings,Latitude,Longitude,Arrest,Domestic,Population,People/Sq.Mile,National Rank,state,location,address,latitude,longitude,chipotle
0,60601,27.0,THEFT,3.0,NaN,NaN,False,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1
1,60601,27.0,CRIMINAL DAMAGE,4.0,41.883932,-87.679964,False,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1
2,60601,27.0,THEFT,3.0,41.896569,-87.636063,False,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1
3,60601,27.0,SEX OFFENSE,3.0,41.883937,-87.683368,True,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1
4,60601,27.0,NARCOTICS,4.0,41.892856,-87.710137,True,False,"5,591","17,101.15",#271,Illinois,Chicago,"316 N Michigan Ave Chicago, IL 60601 US",41.887288,-87.624848,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121081,60661,30.0,OTHER OFFENSE,3.0,41.941430,-87.737110,False,True,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1
121082,60661,30.0,MOTOR VEHICLE THEFT,6.0,NaN,NaN,False,False,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1
121083,60661,30.0,OFFENSE INVOLVING CHILDREN,3.0,41.940857,-87.728919,False,False,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1
121084,60661,30.0,BATTERY,4.0,41.940049,-87.719873,False,True,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1
121085,60661,30.0,ROBBERY,8.0,41.923901,-87.771157,False,False,"4,382","15,455.28",#318,Illinois,Chicago,"525 W Monroe St Ste L1A Chicago, IL 60661 US",41.880364,-87.640869,1

In [13]:
crime_chip_df_filtered.to_csv('Resources/crime_chip_for_model.csv')